language: ruby
env:
  global:
    - TRAVIS=true
  matrix:
    - TASK=rspec
rvm:
  - 2.1.1
services:
  - redis-server
notifications:
  email: false
  webhooks: http://hubot-james.herokuapp.com/hubot/travis?room=#kreisverkehr
