language: ruby
env:
  global:
    - TRAVIS=true
  matrix:
    - TASK=rspec spec
rvm:
  - 2.1.1
services:
  - redis-server
before_script:
  - "cp config/config.yml.example config/config.yml"
  - psql -c "CREATE USER base_app WITH PASSWORD 'password1' CREATEDB;" -U postgres
  - "bundle exec rake db:setup"
  - "bundle exec rake db:seed"
script:
  - "bundle exec $TASK"
notifications:
  email: false
  webhooks: http://hubot-james.herokuapp.com/hubot/travis?room=#kreisverkehr
